package.json, src/components/install/install.js, src/components/update/update.js, src/dockerClient.js, src/main.js
- User will be prompted that they need an internet connection when checking for updates and pulling the Gigantum client
- UI updated to prevent jittery progress bar on Image pull
=> UI Fixes / No internet Connection handling 

package.json, src/config.js, src/gigantum.releaseNotes.md
Changed readme and config to prepare for 0.2.0 release
=> v0.2.0 release

package.json, src/config.js, src/dockerClient.js, src/gigantum.releaseNotes.md
now using /ping to test for connectivity before loading localhost
=> fetch options -> get ping

package.json, src/config.js, src/gigantum.releaseNotes.md
Changed gigantum image to v0.8.2
=> Release 0.3

package.json, src/main.js
fixed bug that would cause electron from halting restart/shut down
=> Interrupt hotfix

package.json, src/config.js, src/dockerClient.js, src/gigantum.releaseNotes.md, src/main.js
Preparing for new release of gigantum client
=> New release (0.4)

package.json, sentry-symbols.js, sentry.properties, src/config.js, src/dockerClient.js, src/gigantum.releaseNotes.md, src/main.js
-Fixed issue with testping function
- changed container configs
- preparing for 0.5.0 release
=> New release (0.5.0)

package.json, src/config.js, src/dockerClient.js, src/gigantum.releaseNotes.md, src/main.js
Fetches nvidia driver version and adds to docker configs if it exists on linux
=> Nvidia config for docker

package.json, src/config.js, src/gigantum.releaseNotes.md
Updating gigantum client to latest version: 0.11.1
=> 0.5.10 Release

src/dockerClient.js
- Project containers will now be cleaned up even if the app closes unexpectedly
- MITM will now be cleaned up along with gmlb- containers
=> Project container cleanup

app/libs/Docker.js, app/libs/Gigantum.js, app/libs/ToolbarInterface.js, app/libs/config.js, app/toolbar/Toolbar.jsx, package.json, yarn.lock
Added toolbar interface to simplify methods being called from the toolbar.
Flushed out start workflow.
=> Toolbar interface

app/ViewManager.jsx, app/assets/css/_base.scss, app/assets/images/icons/notifications/info-exclamation-orange.svg, app/dev-app-update.yml, app/libs/UpdaterInterface.js, app/main.dev.js, app/messenger/MainMessenger.js, app/toolbar/components/common/Buttons.jsx, app/toolbar/components/common/Buttons.scss, app/toolbar/containers/Main.jsx, app/toolbar/messenger/ToolbarMessenger.js, app/updater.js, app/updater/Updater.jsx, app/updater/Updater.scss, app/updater/components/Header.jsx, app/updater/components/Header.scss, app/updater/containers/UpdateAvailable.jsx, app/updater/containers/UpdateAvailable.scss, app/updater/containers/UpdateProgress.jsx, app/updater/machine/UpdaterConstants.js, app/updater/machine/UpdaterMachine.js, app/updater/messenger/UpdaterMessenger.js, configs/webpack.config.renderer.prod.babel.js, package.json, yarn.lock
- basic updater UI initialization
TODO: fix production build to test auto updater functionality
=> Updater UI progress

app/libs/config.js, app/libs/gigantum.releaseNotes.md, configs/webpack.config.base.js, package.json
=> Preparing for 1.0.0 release

app/libs/Docker.js, app/libs/config.js, app/libs/gigantum.releaseNotes.md, configs/webpack.config.base.js, package.json
Config Changes for 1.0.5 release
- small hotfix in stardocker function
=> 1.0.5 Release

app/libs/ToolbarInterface.js, app/libs/containerConfig.js, app/menu.js
Addresses Comments from #114. 
Removes commented code and `console.trace()`.
Removes the following variables from docker env.
```js
const condaDir = 'CONDA_DIR=/opt/conda';
const shell = 'SHELL=/bin/bash';
const miniCondaVersion = 'MINICONDA_VERSION=4.3.31';
const lc = 'LC_ALL=C.UTF-8';
const lang = 'LANG=C.UTF-8';
``` 
Updates bind mount to hostDirectory
```js
const configReturn = (containerDirectory, callback) => {
const Env = [
`HOST_WORK_DIR=${containerDirectory}`,
```
=> Cleanup v1.1.0

app/main.dev.js, app/messenger/MainMessenger.js, package.json
About and Preference windows will now open faster and appear snappier
=> About/Preferences Window performance (#113)

app/app.html, app/main.dev.js, app/messenger/MainMessenger.js, app/server/ManageServer.jsx, app/server/messenger/ServerMessenger.js, app/server/servers/AvailableServers.jsx, app/server/servers/utils/fetchAvailableServers.js
There is now an actual loading screen to replace the blank white screen that appears while the react page is loading
=> Taskbar Loading Screen

app/messenger/MainMessenger.js, app/server/ManageServer.jsx, app/server/messenger/ServerMessenger.js, app/server/servers/AvailableServers.jsx, app/server/servers/utils/fetchAvailableServers.js
Fixed a bug causing manage server modal to white screen on load
Manage server modal will now refetch server list on open
=> Manage server modal fixes

app/libs/config.js, app/libs/containerConfig.js, app/libs/gigantum.releaseNotes.md, configs/webpack.config.base.js, package.json
draft for 1.4.0 client release
=> 1.4.0 Release

app/libs/Installer.js, app/libs/gigantum.releaseNotes.md
- Adds fix path for mac download.
- Adds name change for docker windows install
- Adds docker ps code for windows quick fix
- Adds release notes to release notes file
=> (#166) Adds fixes not captured in master due to release being out of sync

app/installer/components/progressbar/ProgressBar.jsx, app/installer/components/progressbar/circular/CircularProgress.jsx, app/installer/components/progressbar/circular/CircularProgress.scss, app/installer/components/status/ConfigureDockerStatus.jsx, app/installer/components/status/ConfigureGigantumStatus.jsx, app/installer/components/status/InstallDockerStatus.jsx, app/messenger/MainMessenger.js, app/toolbar/containers/Main.jsx
Fixes:
- Progress loader not matching the value in the center of the circle.
- On windows the app was sitting on the taskbar, now sits above it.
- Image jumping in installer on mac
=> (#172, #171, #168) fixes tickets

app/app.html
Browser windows will now have a border added on windows.
=> Added border to views on Windows

app/updater/containers/UpdateProgress.jsx, app/updater/containers/UpdateProgress.scss
There will be a placeholder spinner during the update process. The placeholder is there until the image starts pulling.
=> Download Update spinner

app/installer/components/main/InstallWSL2Main.jsx, app/installer/components/status/InstallWSL2Status.jsx, app/installer/containers/ConfigureGigantum.jsx, app/installer/containers/InstallWSL2.jsx, app/libs/InstallerInterface.js, app/libs/config.js, app/libs/gigantum.releaseNotes.md, app/libs/wslStatus.js, configs/webpack.config.base.js, package.json
- modify wsl command used to check if WSL is enabled
- Option to opt-out of installing kernel if WSL is already enabled
=> Hotfixes issues in 1.3.0 release related to WSL

app/main.dev.js
White tray icon will be used for non-mac devices
=> White tray icon for Linux

app/libs/config.js, app/libs/gigantum.releaseNotes.md, configs/webpack.config.base.js, package.json
changes in preparation for 1.5.3 release
=> 1.5.3 release
